   






  /*
* Created on 2025-02-04 ( 10:23:54 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/ 








    
package org.demo.rest;


import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

                        
import org.demo.Localizacao;
import org.demo.LocalizacaoService;

import org.demo.Estadio;
import org.demo.EstadioService;


@RestController
@RequestMapping("//localizacao")
public class EstadioRestController {

    private EstadioService service;
    private LocalizacaoService localizacaoService;
    private static final Logger LOGGER = LoggerFactory.getLogger(EstadioRestController.class);

    public EstadioRestController(EstadioService service, LocalizacaoService localizacaoService) {
        this.service = service;
        this.localizacaoService = localizacaoService;
    }

    @PostMapping(value="/{id_localizacao}/Estadio", consumes = {MediaType.APPLICATION_JSON_VALUE}, produces = {MediaType.APPLICATION_JSON_VALUE})
        public ResponseEntity<?> save(@PathVariable("id_localizacao") Long idLocalizacao, @RequestBody EstadioRequest request){
        LOGGER.info("Iniciando criação de um novo Estadio para Localizacao com ID: {}", idLocalizacao);
        if (idLocalizacao == null){
            return ResponseEntity.badRequest().body("idLocalizacao está inválido");
        }

        Set< String > validations = request.isValidOnStage(ValidOnCreation.class);
        if(request == null){
            return ResponseEntity.badRequest().body("Não há dados para serem cadastrados");
        }
        if (!validations.isEmpty()) {
            return ResponseEntity.badRequest().body(validations);
        }

        Optional<Localizacao> possivelLocalizacao = this.localizacaoService.findById(idLocalizacao);
        if(possivelLocalizacao.isPresent()){
            Localizacao localizacao = possivelLocalizacao.get();
            Estadio object = request.transform(localizacao);
            service.save(object);
            LOGGER.info("Estadio criado para Localizacao com sucesso!");
            return ResponseEntity.ok().header("Custom-Header", "foo").body(object);
        }
        else{
            LOGGER.info("localizacao não encontrado com ID: {}", idLocalizacao);
            return ResponseEntity.notFound().header("not-found-id", String.valueOf(idLocalizacao)).build();
        }

    }

    @GetMapping(value="/{id_localizacao}/Estadio", produces= {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<?> findAll(@PathVariable("id_localizacao") Long idLocalizacao) {
        LOGGER.info("Buscando lista de Estadio");

        if (idLocalizacao == null){
            return ResponseEntity.badRequest().body("idLocalizacao está inválido");
        }

        List<Estadio> list = service.findAll();
        LOGGER.info("Estadio encontrados: {}", list.size());
        return ResponseEntity.ok().header("Custom-Header", "foo").body(list);
    }

    @GetMapping(value="/{id_localizacao}/Estadio/{id}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<?> findById(@PathVariable("id_localizacao") Long idLocalizacao, @PathVariable("id") Long id){
        LOGGER.info("Buscando Estadio por id: {}", id);

        if (idLocalizacao == null){
            return ResponseEntity.badRequest().body("idLocalizacao está inválido");
        }

        if(id == null){
            return ResponseEntity.badRequest().body("id inválido");
        }

        Optional<Estadio> object = service.findById(id);
        if (object.isPresent()) {
            LOGGER.info("Estadio encontrado com sucesso: {}");
            return ResponseEntity.ok().header("Custom-header", "foo").body(object.get());
        }else{
            LOGGER.info("Estadio não encontrado pelo id: {}", id);
            return ResponseEntity.notFound().header("not-found-id", String.valueOf(id)).build();
        }
    }
           
    @PutMapping(value="/{id_localizacao}/Estadio", consumes = {MediaType.APPLICATION_JSON_VALUE}, produces= {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<?> update(@PathVariable("id_localizacao") Long idLocalizacao, @RequestBody EstadioRequest request) {
        LOGGER.info("Iniciando atualização de Estadio pelo id: {}", request.getId());

        Set< String > validations = request.isValidOnStage(ValidOnUpdate.class);
        if (!validations.isEmpty()) {
            return ResponseEntity.badRequest().body(validations);
        }

        Optional<Localizacao> possivelLocalizacao = this.localizacaoService.findById(idLocalizacao);
        Optional<Estadio> possivelObject = service.findById(request.getId());
        if(possivelObject.isPresent()){
            Estadio object = request.transform(possivelLocalizacao.get());
            service.update(object);
            LOGGER.info("Estadio atualizado(a) com sucesso: {}", object.logString());
            return ResponseEntity.ok().header("Custom-Header", "foo").body(object);
        } else{
            LOGGER.info("Estadio não encontrado(a) pelo id: {}", request.getId());
            return ResponseEntity.notFound().header("not-found-id", String.valueOf(request.getId())).build();
        }
    }


    @DeleteMapping(value="/{id_localizacao}/Estadio/{id}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<?> delete(@PathVariable("id_localizacao") Long idLocalizacao, @PathVariable("id") Long id) {
        LOGGER.info("Iniciando deleção de Estadio pelo id: {}", id);
        Optional<Estadio> possivelObject = service.findById(id);
        Estadio object = possivelObject.get();
        service.delete(object);
        LOGGER.info("Estadio deletado(a) com sucesso: {}", object.logString());
        return ResponseEntity.ok().header("Custom-Header", "foo").body(object);
    }

}


